# Copyright (c) 2019 The Ste||ar Group
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

language: cpp

os:
  - windows
  - osx

git:
  depth: 1

branches:
  except:
  - gh-pages

install:
  - ./tools/travis/install_dependencies.sh

before_script:
  - ./tools/travis/configure.sh

script:
  - ./tools/travis/build_and_run_tests.sh
